licenses(["notice"])  # Apache 2.0

java_binary(
    name = "JavaSourceFileParserCli",
    main_class = "com.google.devtools.build.bfg.JavaSourceFileParserCli",
    runtime_deps = ["//lang/java/src/main/java/com/google/devtools/build/bfg:JavaSourceFileParser"],
)
