licenses(["notice"])  # Apache 2.0

package(default_visibility = [
    "//visibility:private",
])

java_binary(
    name = "bfg",
	main_class = "com.google.devtools.build.bfg.Bfg",
	stamp = 1,
	runtime_deps = ["//src/main/java/com/google/devtools/build/bfg:Bfg"],
)
